### ISSUE TITLE
how to use in angular

### ISSUE THREAD

**Issue by aizhang** [kswedberg/jquery-expander#101]
could you give a simple example? thanks

**Comment by travco** [comment]
This is likely long-past the time where it will be useful for the OP, but **for future readers of this issue** I would say it is strongly disadvised to try to use this expander in angular. To do so would require workarounds that would negate most of the advantages angular attempts to achieve. Not to mention there are already [readily-availible prebuilt modules in angular that do quite similar things](http://angular-ui.github.io/bootstrap/#/collapse.) to jquery-expander.

**Comment by kswedberg** [comment]
Thanks @travco (even though that link only brings me to a blank page). I'm closing this issue, since it's not really something I think we should be concerning ourselves with for this plugin.
