### ISSUE TITLE
Scroll back up after triggering "read less"

### ISSUE THREAD

**Issue by djmtype** [kswedberg/jquery-expander#102]
When there is *alot* of content, after clicking the "read less" link, what would be the callback function in order to have this plugin scroll back up to the place where the text begins?

**Comment by kswedberg** [comment]
@djmtype : Sorry for not getting back to you sooner. You'd use the `afterCollapse` callback.

**Comment by kswedberg** [comment]
Closing this as answered.

**Comment by Jimmyleg** [comment]
thank you @kswedberg

**Comment by kswedberg** [comment]
you bet!
