### ISSUE TITLE
An option to start expanded would be useful

### ISSUE THREAD

**Issue by adammessinger** [kswedberg/jquery-expander#103]
A boolean option like `startExpanded` would be great for a use case I have. This would start the block expanded, but still allow it to be collapsed by the user.

**Comment by lolomet** [comment]
+1. Especially if we can hit it with a URL.

**Comment by lolomet** [comment]
BTW, you can just simulate the clicking with a `#ID` in the URL like so:

```
if (window.location.href.indexOf('#') > -1)
    var url = /#(\d+)/.exec(location.href) + '',
	  id = url.split(',')[1]

	  if (id)
              console.log('Clicking ID: ' + id)
              $('.pub_' + id).find('.read-more a').click()
```

**Comment by kswedberg** [comment]
Thanks for the reports. I'll try to look into this over the weekend.

**Comment by kswedberg** [comment]
Added `startExpanded` option in c9985517db26fbf138f1f609670f5ac970372998. Enjoy!
