### ISSUE TITLE
Issues with \n and white-space: pre-line;

### ISSUE THREAD

**Issue by ZaneCEO** [kswedberg/jquery-expander#116]
Hello,
my webapp uses `white-space: pre-line;` to create linebreaks from the "\n" terminator even if the text has no BR or P.

It works as intended on its own, but as soon as I add jquery-expander to the text block it goes south: see my example here https://jsfiddle.net/sexyzane/4a0tuwuv/2/ and note how the second text block has the linefeed destroyed.

Any thoughts, workarounds or solutions? Thanks!

**Comment by kswedberg** [comment]
@ZaneCEO thanks for providing an example. I'll take a look as soon as I can. Feel free to ping me if you don't hear anything within a few days, though.

**Comment by kswedberg** [comment]
@ZaneCEO you're using a pretty old version of the plugin. Can you try it with the most recent version? I tested it locally, and it didn't seem to have a problem.

**Comment by ZaneCEO** [comment]
I'll test it immediately...

**Comment by ZaneCEO** [comment]
You are definitely right: as soon as I updated, the problem disappeard: https://jsfiddle.net/4a0tuwuv/3/ 

So... this is the second time that you solved a problem of mine. If you come to Ferrara (Italy), please stop by for a glass of wine: I definitely owe you one! Meanwhile, my sincere thanks!

**Comment by kswedberg** [comment]
Ha! Well, if I'm ever in the area, I just might take you up on the offer. :)

Happy to hear that it's working for you now.

**Comment by ZaneCEO** [comment]
Two years later, I come back to your plugin for another project. It still works like a charm, thanks!

A note to whoever may have my same problem with `white-space` not respected: you also need to set `normalizeWhitespace: false` in the config, like so:

```
        jQuery('#adv-description').expander({
            ...
            normalizeWhitespace: false
...
        });
```
