### ISSUE TITLE
not working when i set data using ajax

### ISSUE THREAD

**Issue by socialinfotech215** [kswedberg/jquery-expander#123]
not working when i set data using ajax so how can i solve this issue?...

**Comment by kswedberg** [comment]
I'm not sure exactly what the circumstances are. If you could provide some code that shows the problem, that would be helpful. 

One thing to note, though, is that the content has to be in the document before you can act on it. So if you are inserting content with ajax, you should call `.expander()` on that content in a callback after it has been inserted. Something like:

```js
$.ajax('/some/content')
.then(function(html) {
  $(html).appendTo('#mydiv');
  $('#mydiv').find('.something-to-expand').expander();
})
```

**Comment by socialinfotech215** [comment]
thanks.. 
but how can i stop load content when first time page load??
