### ISSUE TITLE
Duplicate text when  Normalizewhite space = false

### ISSUE THREAD

**Issue by hardeep360** [kswedberg/jquery-expander#147]
Hello,

Can you please add this to line 472 as if there is multiple spaces on start of the text then for summery text they are gone and duplicate text start to show as text length mismatches with summarytext and full html text?
<img width="355" alt="Screenshot 2024-05-13 at 22 00 46" src="https://github.com/kswedberg/jquery-expander/assets/8924821/26bb604c-1b0f-4807-8b03-3621d2e7bef0">

Line: 472, backup(txt, preserveWords)
return opts.normalizeWhitespace ? txt.replace(rTrim, '') : txt;

**Comment by kswedberg** [comment]
thanks for the report. I will look into it as soon as I can
